version: '3'

services:
  cr_cassandra1:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: CR_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cr_cassandra1_data:/var/lib/cassandra

volumes:
  cr_mongodb_data:
  cr_cassandra1_data:
