version: '3'

services:
  cr_cassandra1:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: CR_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cr_cassandra1_data:/var/lib/cassandra

  cr_cassandra2:
    image: cassandra:4.1.3
    environment:
      CASSANDRA_CLUSTER_NAME: CR_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: cr_cassandra1
    volumes:
      - cr_cassandra2_data:/var/lib/cassandra

  cr_cassandra3:
    image: cassandra:4.1.3
    environment:
      CASSANDRA_CLUSTER_NAME: CR_CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: cr_cassandra1
    volumes:
      - cr_cassandra3_data:/var/lib/cassandra

volumes:
  cr_mongodb_data:
  cr_cassandra1_data:
  cr_cassandra2_data:
  cr_cassandra3_data:
