version: '3'

services:
  cassandra1:
    image: cassandra:4.1.3
    container_name: cassandra1
    hostname: cassandra1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: CLUSTER
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra1_data:/var/lib/cassandra

volumes:
  cassandra1_data:
